// Single place that queries the DOM, so markup ids only need to stay in sync
// here. Modules import `dom` instead of calling getElementById themselves.

export const dom = {
    // Top bar
    aspectBtns: Array.from(document.querySelectorAll('.aspect-btn')),
    clearCanvasBtn: document.getElementById('clearCanvasBtn'),
    exportBtn: document.getElementById('exportBtn'),
    exportDropdown: document.getElementById('exportDropdown'),
    exportMenu: document.getElementById('exportMenu'),
    exportMenuItems: Array.from(document.querySelectorAll('.export-menu-item')),
    exportQualityRow: document.getElementById('exportQualityRow'),
    exportQualityBtns: Array.from(document.querySelectorAll('.export-quality-btn')),

    // Toolbox
    addTextTool: document.getElementById('addTextTool'),
    imageUploadInput: document.getElementById('imageUploadInput'),
    bgColorTool: document.getElementById('bgColorTool'),
    bgColorInput: document.getElementById('canvasBgColor'),
    bgDropdown: document.getElementById('bgDropdown'),

    bgGradientClearBtn: document.getElementById('bgGradientClearBtn'),
    openGradientEditorBtn: document.getElementById('openGradientEditorBtn'),
    currentGradientRow: document.getElementById('currentGradientRow'),
    currentGradientPreview: document.getElementById('currentGradientPreview'),
    undoTool: document.getElementById('undoTool'),
    redoTool: document.getElementById('redoTool'),
    svgPickerTool: document.getElementById('svgPickerTool'),
    importSvgTool: document.getElementById('importSvgTool'),
    importSvgDropdown: document.getElementById('importSvgDropdown'),
    importSvgLocalOption: document.getElementById('importSvgLocalOption'),
    importSvgPasteOption: document.getElementById('importSvgPasteOption'),
    importSvgFileInput: document.getElementById('importSvgFileInput'),
    importSvgPasteBackdrop: document.getElementById('importSvgPasteBackdrop'),
    importSvgPasteInput: document.getElementById('importSvgPasteInput'),
    importSvgPasteClose: document.getElementById('importSvgPasteClose'),
    importSvgPasteCancel: document.getElementById('importSvgPasteCancel'),
    importSvgPasteConfirm: document.getElementById('importSvgPasteConfirm'),
    importHtmlOption: document.getElementById('importHtmlOption'),
    importHtmlFileInput: document.getElementById('importHtmlFileInput'),

    // HTML Inject
    htmlInjectTool: document.getElementById('htmlInjectTool'),
    htmlInjectBackdrop: document.getElementById('htmlInjectBackdrop'),
    htmlInjectClose: document.getElementById('htmlInjectClose'),
    htmlInjectTabCode: document.getElementById('htmlInjectTabCode'),
    htmlInjectTabFile: document.getElementById('htmlInjectTabFile'),
    htmlInjectCodePanel: document.getElementById('htmlInjectCodePanel'),
    htmlInjectFilePanel: document.getElementById('htmlInjectFilePanel'),
    htmlInjectInput: document.getElementById('htmlInjectInput'),
    htmlInjectDropZone: document.getElementById('htmlInjectDropZone'),
    htmlInjectFileInput: document.getElementById('htmlInjectFileInput'),
    htmlInjectCancel: document.getElementById('htmlInjectCancel'),
    htmlInjectConfirm: document.getElementById('htmlInjectConfirm'),
    selectTool: document.getElementById('selectTool'),
    selectMenu: document.getElementById('selectMenu'),
    selectCopyBtn: document.getElementById('selectCopyBtn'),
    selectPasteBtn: document.getElementById('selectPasteBtn'),

    // Canvas area
    canvasArea: document.getElementById('canvasArea'),
    canvasWrapper: document.getElementById('canvasWrapper'),
    designCanvas: document.getElementById('designCanvas'),
    marqueeSelection: document.getElementById('marqueeSelection'),
    elementFab: document.getElementById('elementFab'),
    fabMenuBtn: document.getElementById('fabMenuBtn'),
    fabMenu: document.getElementById('fabMenu'),

    // Page track (multi-canvas)
    pageTrack: document.getElementById('pageTrack'),
    pageThumbs: document.getElementById('pageThumbs'),
    addPageBtn: document.getElementById('addPageBtn'),
    clonePageBtn: document.getElementById('clonePageBtn'),
    deletePageBtn: document.getElementById('deletePageBtn'),

    // Properties panel
    noSelection: document.getElementById('noSelection'),
    multiSelectionNote: document.getElementById('multiSelectionNote'),
    positionProperties: document.getElementById('positionProperties'),
    positionXInput: document.getElementById('positionXInput'),
    positionYInput: document.getElementById('positionYInput'),
    sizeWidthInput: document.getElementById('sizeWidthInput'),
    sizeHeightInput: document.getElementById('sizeHeightInput'),
    rotationInput: document.getElementById('rotationInput'),
    skewXInput: document.getElementById('skewXInput'),
    skewYInput: document.getElementById('skewYInput'),
    textProperties: document.getElementById('textProperties'),
    imageProperties: document.getElementById('imageProperties'),
    textContentInput: document.getElementById('textContentInput'),
    fontSizeInput: document.getElementById('fontSizeInput'),
    fontWeightInput: document.getElementById('fontWeightInput'),
    fontFamilyInput: document.getElementById('fontFamilyInput'),
    customFontInput: document.getElementById('customFontInput'),
    customFontHint: document.getElementById('customFontHint'),
    textColorInput: document.getElementById('textColorInput'),
    textColorGradientBtn: document.getElementById('textColorGradientBtn'),
    textBgColorInput: document.getElementById('textBgColorInput'),
    textBgGradientBtn: document.getElementById('textBgGradientBtn'),
    removeTextBgBtn: document.getElementById('removeTextBgBtn'),
    paddingTopInput: document.getElementById('paddingTopInput'),
    paddingRightInput: document.getElementById('paddingRightInput'),
    paddingBottomInput: document.getElementById('paddingBottomInput'),
    paddingLeftInput: document.getElementById('paddingLeftInput'),
    shadowPresetInput: document.getElementById('shadowPresetInput'),
    shadowXInput: document.getElementById('shadowXInput'),
    shadowYInput: document.getElementById('shadowYInput'),
    shadowBlurInput: document.getElementById('shadowBlurInput'),
    shadowColorInput: document.getElementById('shadowColorInput'),
    shadowOpacityInput: document.getElementById('shadowOpacityInput'),
    shadowOpacityLabel: document.getElementById('shadowOpacityLabel'),
    textShadowInput: document.getElementById('textShadowInput'),
    removeShadowBtn: document.getElementById('removeShadowBtn'),
    brTLInput: document.getElementById('brTLInput'),
    brTRInput: document.getElementById('brTRInput'),
    brBLInput: document.getElementById('brBLInput'),
    brBRInput: document.getElementById('brBRInput'),
    deleteElementBtn: document.getElementById('deleteElementBtn'),
    deleteImageBtn: document.getElementById('deleteImageBtn'),
    swapImageInput: document.getElementById('swapImageInput'),
    svgProperties: document.getElementById('svgProperties'),
    svgFillColorInput: document.getElementById('svgFillColorInput'),
    svgFillColorHex: document.getElementById('svgFillColorHex'),
    removeSvgFillBtn: document.getElementById('removeSvgFillBtn'),
    svgStrokeInput: document.getElementById('svgStrokeInput'),
    svgStrokeValue: document.getElementById('svgStrokeValue'),
    svgBlurXInput: document.getElementById('svgBlurXInput'),
    svgBlurXValue: document.getElementById('svgBlurXValue'),
    svgBlurYInput: document.getElementById('svgBlurYInput'),
    svgBlurYValue: document.getElementById('svgBlurYValue'),
    svgGhostBlurXInput: document.getElementById('svgGhostBlurXInput'),
    svgGhostBlurXValue: document.getElementById('svgGhostBlurXValue'),
    svgGhostBlurYInput: document.getElementById('svgGhostBlurYInput'),
    svgGhostBlurYValue: document.getElementById('svgGhostBlurYValue'),
    svgGhostOffXInput: document.getElementById('svgGhostOffXInput'),
    svgGhostOffXValue: document.getElementById('svgGhostOffXValue'),
    svgGhostOffYInput: document.getElementById('svgGhostOffYInput'),
    svgGhostOffYValue: document.getElementById('svgGhostOffYValue'),
    svgGhostOpacityInput: document.getElementById('svgGhostOpacityInput'),
    svgGhostOpacityValue: document.getElementById('svgGhostOpacityValue'),
    svgGradientTypeInput: document.getElementById('svgGradientTypeInput'),
    svgGradientColorInput: document.getElementById('svgGradientColorInput'),
    svgGradientColorHex: document.getElementById('svgGradientColorHex'),
    removeSvgGradientBtn: document.getElementById('removeSvgGradientBtn'),
    gradientStopsList: document.getElementById('gradientStopsList'),
    addGradientStopBtn: document.getElementById('addGradientStopBtn'),
    svgGradientAngleInput: document.getElementById('svgGradientAngleInput'),
    svgGradientAngleValue: document.getElementById('svgGradientAngleValue'),
    svgGradientOpacityInput: document.getElementById('svgGradientOpacityInput'),
    svgGradientOpacityValue: document.getElementById('svgGradientOpacityValue'),
    svgGradientCssInput: document.getElementById('svgGradientCssInput'),
    copySvgGradientCssBtn: document.getElementById('copySvgGradientCssBtn'),
    resetSvgPropsBtn: document.getElementById('resetSvgPropsBtn'),
    deleteSvgBtn: document.getElementById('deleteSvgBtn'),

    // Context menu
    contextMenu: document.getElementById('contextMenu'),
    fitModeMenuItem: document.getElementById('fitModeMenuItem'),
};
